const rgInit = [
	new Land("Mountain","Mountain","Library",false,"http://gatherer.wizards.com/Handlers/Image.ashx?type=card&multiverseid=386610"),
	new Land("Mountain","Mountain","Library",false,"http://gatherer.wizards.com/Handlers/Image.ashx?type=card&multiverseid=386610"),
	new Land("Mountain","Mountain","Library",false,"http://gatherer.wizards.com/Handlers/Image.ashx?type=card&multiverseid=386610"),
	new Land("Mountain","Mountain","Library",false,"http://gatherer.wizards.com/Handlers/Image.ashx?type=card&multiverseid=386610"),
	new Land("Mountain","Mountain","Library",false,"http://gatherer.wizards.com/Handlers/Image.ashx?type=card&multiverseid=386610"),
	new Land("Mountain","Mountain","Library",false,"http://gatherer.wizards.com/Handlers/Image.ashx?type=card&multiverseid=386610"),
	new Land("Mountain","Mountain","Library",false,"http://gatherer.wizards.com/Handlers/Image.ashx?type=card&multiverseid=386610"),
	new Land("Forest","Forest","Library",false,"http://gatherer.wizards.com/Handlers/Image.ashx?type=card&multiverseid=373625"),
	new Land("Forest","Forest","Library",false,"http://gatherer.wizards.com/Handlers/Image.ashx?type=card&multiverseid=373625"),
	new Land("Forest","Forest","Library",false,"http://gatherer.wizards.com/Handlers/Image.ashx?type=card&multiverseid=373625"),
	new Land("Forest","Forest","Library",false,"http://gatherer.wizards.com/Handlers/Image.ashx?type=card&multiverseid=373625"),
	new Land("Forest","Forest","Library",false,"http://gatherer.wizards.com/Handlers/Image.ashx?type=card&multiverseid=373625"),
	new Land("Forest","Forest","Library",false,"http://gatherer.wizards.com/Handlers/Image.ashx?type=card&multiverseid=373625"),
	new Land("Forest","Forest","Library",false,"http://gatherer.wizards.com/Handlers/Image.ashx?type=card&multiverseid=373625"),
	new Creature("Woodland Druid",[0,0,0,0,1,0,0],1,2,"Library",false,false,false,false,0,"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=29772&type=card"),
	new Creature("Woodland Druid",[0,0,0,0,1,0,0],1,2,"Library",false,false,false,false,0,"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=29772&type=card"),
	new Creature("Grizzly Bears",[0,0,0,0,1,1,0],2,2,"Library",false,false,false,false,0,"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129586&type=card"),
	new Creature("Grizzly Bears",[0,0,0,0,1,1,0],2,2,"Library",false,false,false,false,0,"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129586&type=card"),
	new Creature("Grizzly Bears",[0,0,0,0,1,1,0],2,2,"Library",false,false,false,false,0,"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129586&type=card"),
	new Creature("Grizzly Bears",[0,0,0,0,1,1,0],2,2,"Library",false,false,false,false,0,"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129586&type=card"),
	new Creature("Frenzied Raptor",[0,0,0,1,0,2,0],4,2,"Library",false,false,false,false,0,"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=435300&type=card"),
	new Creature("Frenzied Raptor",[0,0,0,1,0,2,0],4,2,"Library",false,false,false,false,0,"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=435300&type=card"),
	new Creature("Lowland Giant",[0,0,0,2,0,2,0],4,3,"Library",false,false,false,false,0,"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=4829&type=card"),
	new Creature("Lowland Giant",[0,0,0,2,0,2,0],4,3,"Library",false,false,false,false,0,"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=4829&type=card"),
	new Creature("Hulking Devil",[0,0,0,1,0,3,0],5,2,"Library",false,false,false,false,0,"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=409919&type=card"),
	new Creature("Hulking Devil",[0,0,0,1,0,3,0],5,2,"Library",false,false,false,false,0,"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=409919&type=card"),
	new Creature("Rhox Brute",[0,0,0,1,1,2,0],4,4,"Library",false,false,false,false,0,"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=189650&type=card"),
	new Creature("Rhox Brute",[0,0,0,1,1,2,0],4,4,"Library",false,false,false,false,0,"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=189650&type=card"),
	new Creature("Ruination Wurm",[0,0,0,1,1,4,0],7,6,"Library",false,false,false,false,0,"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=366235&type=card"),
	new Creature("Ancient Brontodon",[0,0,0,0,2,6,0],9,9,"Library",false,false,false,false,0,"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=435330&type=card")
]

const uwInit = [
	new Land("Plains","Plains","Library",false,"http://gatherer.wizards.com/Handlers/Image.ashx?type=card&multiverseid=373582"),
	new Land("Plains","Plains","Library",false,"http://gatherer.wizards.com/Handlers/Image.ashx?type=card&multiverseid=373582"),
	new Land("Plains","Plains","Library",false,"http://gatherer.wizards.com/Handlers/Image.ashx?type=card&multiverseid=373582"),
	new Land("Plains","Plains","Library",false,"http://gatherer.wizards.com/Handlers/Image.ashx?type=card&multiverseid=373582"),
	new Land("Plains","Plains","Library",false,"http://gatherer.wizards.com/Handlers/Image.ashx?type=card&multiverseid=373582"),
	new Land("Plains","Plains","Library",false,"http://gatherer.wizards.com/Handlers/Image.ashx?type=card&multiverseid=373582"),
	new Land("Plains","Plains","Library",false,"http://gatherer.wizards.com/Handlers/Image.ashx?type=card&multiverseid=373582"),
	new Land("Island","Island","Library",false,"http://gatherer.wizards.com/Handlers/Image.ashx?type=card&multiverseid=435426"),
	new Land("Island","Island","Library",false,"http://gatherer.wizards.com/Handlers/Image.ashx?type=card&multiverseid=435426"),
	new Land("Island","Island","Library",false,"http://gatherer.wizards.com/Handlers/Image.ashx?type=card&multiverseid=435426"),
	new Land("Island","Island","Library",false,"http://gatherer.wizards.com/Handlers/Image.ashx?type=card&multiverseid=435426"),
	new Land("Island","Island","Library",false,"http://gatherer.wizards.com/Handlers/Image.ashx?type=card&multiverseid=435426"),
	new Land("Island","Island","Library",false,"http://gatherer.wizards.com/Handlers/Image.ashx?type=card&multiverseid=435426"),
	new Land("Island","Island","Library",false,"http://gatherer.wizards.com/Handlers/Image.ashx?type=card&multiverseid=435426"),
	new Creature("Savannah Lions",[1,0,0,0,0,0,0],2,1,"Library",false,false,false,false,0,"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442022&type=card"),
	new Creature("Savannah Lions",[1,0,0,0,0,0,0],2,1,"Library",false,false,false,false,0,"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442022&type=card"),
	new Creature("Seagraf Skaab",[0,1,0,0,0,1,0],1,3,"Library",false,false,false,false,0,"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=409827&type=card"),
	new Creature("Knight of New Benalia",[1,0,0,0,0,1,0],3,1,"Library",false,false,false,false,0,"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442912&type=card"),
	new Creature("Knight of New Benalia",[1,0,0,0,0,1,0],3,1,"Library",false,false,false,false,0,"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442912&type=card"),
	new Creature("Tolarian Scholar",[0,1,0,0,0,2,0],2,3,"Library",false,false,false,false,0,"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=447216&type=card"),
	new Creature("Tolarian Scholar",[0,1,0,0,0,2,0],2,3,"Library",false,false,false,false,0,"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=447216&type=card"),
	new Creature("Those Who Serve",[1,0,0,0,0,2,0],2,4,"Library",false,false,false,false,0,"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=426734&type=card"),
	new Creature("Those Who Serve",[1,0,0,0,0,2,0],2,4,"Library",false,false,false,false,0,"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=426734&type=card"),
	new Creature("Wishcoin Crab",[0,1,0,0,0,3,0],2,5,"Library",false,false,false,false,0,"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=452810&type=card"),
	new Creature("Wishcoin Crab",[0,1,0,0,0,3,0],2,5,"Library",false,false,false,false,0,"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=452810&type=card"),
	new Creature("Giant Octopus",[0,1,0,0,0,3,0],3,3,"Library",false,false,false,false,0,"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=83104&type=card"),
	new Creature("Giant Octopus",[0,1,0,0,0,3,0],3,3,"Library",false,false,false,false,0,"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=83104&type=card"),
	new Creature("Indomitable Ancients",[2,0,0,0,0,2,0],2,10,"Library",false,false,false,false,0,"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=152967&type=card"),
	new Creature("Thraben Purebloods",[1,0,0,0,0,4,0],3,5,"Library",false,false,false,false,0,"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=230625&type=card"),
	new Creature("Vizzerdrix",[0,1,0,0,0,6,0],7,7,"Library",false,false,false,false,0,"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=94911&type=card")
]
